export const SyntaxType = {
  KEYWORD: 'KEYWORD',
  PUNCTUATION: 'PUNCTUATION',
  COMMENT: 'COMMENT',
  STRING: 'STRING',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  CUSTOM1: 'CUSTOM1',
  CUSTOM2: 'CUSTOM2',
  CUSTOM3: 'CUSTOM3',
  CUSTOM4: 'CUSTOM4',
};
